version: "3.9"

services:
  app: # PHP-FPM (runs Artisan, Composer, Queues)
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    depends_on:
      - db
      - redis

  web: # Nginx
    image: nginx:alpine
    container_name: laravel-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  node: # Vite dev server (hot reload)
    image: node:20-alpine
    container_name: laravel-node
    working_dir: /var/www/html
    command: sh -c "npm ci && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app

  db: # MySQL
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306" # expose if you want to connect with a GUI
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
      # Ensures compatibility with Laravel defaults
      MYSQL_TCP_PORT: 3306
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"

volumes:
  db-data: